Alex/bugfix
ScottyLabs/tartanhacks-registration pull request #191
Opened 2023-01-29 00:34 UTC by pm3512

# Description

Adds waitlist banner

2023-01-29 20:59 UTC, anudaweerasinghe requested changes

2023-01-29 20:59 UTC, anudaweerasinghe commented on src/components/confirmation/ConfirmationDialog/index.tsx
> +        <Typography
When we accept people off the waitlist, they'll need to confirm using this form. So we shouldn't remove it.

Instead, when a user goes to `/confirmation` check that their `status=CONFIRMED`. If not, automatically redirect to `/`

2023-01-29 20:59 UTC, anudaweerasinghe commented on src/components/menu/Menu/index.tsx
> +            {status === Status.ADMITTED && !isLate ? (
Can remove this since we'll be moving everyone from `ADMITTED` to `COMPLETED_PROFILE` after the deadline.

And people that get off the waitlist should be able to confirm

2023-01-30 04:35 UTC, gramliu approved these changes

2023-01-30 04:45 UTC, merged